'use strict';
module.exports = [
  {
    num: 1,
    fileOut: 'Y5_Sp_T1_L01_LaCaraYLaCabeza.pptx',
    titleSp: 'La cara y la cabeza',
    titleEng: 'The face and head',
    lo: 'Puedo nombrar las partes de la cara en español.',
    loEng: 'I can name parts of the face in Spanish.',
    phonicsLetter: 'H',
    phonicsSound: 'Silent — never pronounced',
    phonicsFact: 'In Spanish, H is completely silent. You never say it.',
    phonicsExamples: [
      { word: 'Hola', pron: 'OH-lah', eng: 'Hello' },
      { word: 'hombro', pron: 'OM-broh', eng: 'shoulder' },
      { word: 'hay', pron: 'eye', eng: 'there is/are' },
    ],
    counting: {
      label: '1 al 10',
      nums: [
        {n:'1',sp:'uno'},{n:'2',sp:'dos'},{n:'3',sp:'tres'},
        {n:'4',sp:'cuatro'},{n:'5',sp:'cinco'},
        {n:'6',sp:'seis'},{n:'7',sp:'siete'},{n:'8',sp:'ocho'},
        {n:'9',sp:'nueve'},{n:'10',sp:'diez'},
      ]
    },
    warmUp: {
      title: '¡Buenos días!',
      instruction: 'Greet your partner and ask how they feel. Try three different people!',
      sentence1: '¿Cómo estás?   →   Estoy bien / mal / así así',
      response: 'How many people can you greet before the timer runs out?',
    },
    vocab: [
      { sp: 'la cabeza', pron: 'lah kah-BEH-thah', eng: 'head' },
      { sp: 'los ojos', pron: 'loss OH-hoss', eng: 'eyes' },
      { sp: 'la boca', pron: 'lah BOH-kah', eng: 'mouth' },
      { sp: 'la nariz', pron: 'lah nah-REETH', eng: 'nose' },
      { sp: 'las orejas', pron: 'lass oh-REH-hass', eng: 'ears' },
    ],
    keyStructure: '¿Qué es esto?   —   Es la nariz.',
    cultural: {
      heading: 'El español en el mundo',
      fact: 'Spanish is spoken by over 500 million people across 20+ countries.',
      detail: 'It is the 2nd most widely spoken language in the world by native speakers!',
    },
    activities: [
      {
        title: 'Señalad y decid',
        icon: '👆',
        instruction: 'Teacher says a body part in Spanish — point to it on your own face. Then say the word.',
        examples: ['Señalad la nariz!', 'Señalad los ojos!'],
        tip: null,
      },
      {
        title: 'Simón dice...',
        icon: '🎮',
        instruction: 'Play Simon Says! Only move when you hear Simón dice first.',
        examples: ['Simón dice: ¡tocad la nariz!', 'Simón dice: ¡cerrad los ojos!'],
        tip: null,
      },
      {
        title: 'Etiquetad la cara',
        icon: '✏️',
        instruction: 'Label the face diagram — write the correct Spanish word next to each arrow.',
        examples: null,
        tip: 'Use your vocab from today. Can you write all 5?',
      },
    ],
    roundOff: '¿Cómo se dice NOSE? EYES? MOUTH? Tell your partner — then point and show!',
    imgFile: null,
  },
  {
    num: 2,
    fileOut: 'Y5_Sp_T1_L02_BrazosYManos.pptx',
    titleSp: 'Los brazos y las manos',
    titleEng: 'Arms and hands',
    lo: 'Puedo nombrar los brazos, las manos y los hombros.',
    loEng: 'I can name arms, hands, fingers and shoulders in Spanish.',
    phonicsLetter: 'B',
    phonicsSound: 'B and V sound the same!',
    phonicsFact: 'In Spanish, B and V make exactly the same sound — a soft English "b". There is no "v" sound.',
    phonicsExamples: [
      { word: 'brazo', pron: 'BRAH-thoh', eng: 'arm' },
      { word: 'boca', pron: 'BOH-kah', eng: 'mouth' },
      { word: 'veinte', pron: 'BAYN-teh', eng: 'twenty' },
    ],
    counting: {
      label: '1 al 20',
      nums: [
        {n:'1',sp:'uno'},{n:'2',sp:'dos'},{n:'3',sp:'tres'},
        {n:'4',sp:'cuatro'},{n:'5',sp:'cinco'},
        {n:'6',sp:'seis'},{n:'7',sp:'siete'},{n:'8',sp:'ocho'},
        {n:'9',sp:'nueve'},{n:'10',sp:'diez'},
        {n:'11',sp:'once'},{n:'12',sp:'doce'},{n:'13',sp:'trece'},
        {n:'14',sp:'catorce'},{n:'15',sp:'quince'},
        {n:'16',sp:'dieciséis'},{n:'17',sp:'diecisiete'},{n:'18',sp:'dieciocho'},
        {n:'19',sp:'diecinueve'},{n:'20',sp:'veinte'},
      ]
    },
    warmUp: {
      title: 'Repaso rápido',
      instruction: 'Partner quiz! Point to a body part — your partner says it in Spanish. Then swap.',
      sentence1: 'La cabeza  ·  los ojos  ·  la boca  ·  la nariz  ·  las orejas',
      response: 'How many can you name without looking at your notes?',
    },
    vocab: [
      { sp: 'el brazo', pron: 'el BRAH-thoh', eng: 'arm' },
      { sp: 'la mano', pron: 'lah MAH-noh', eng: 'hand' },
      { sp: 'los dedos', pron: 'loss DEH-doss', eng: 'fingers' },
      { sp: 'el hombro', pron: 'el OM-broh', eng: 'shoulder' },
      { sp: 'el cuello', pron: 'el KWEH-yoh', eng: 'neck' },
    ],
    keyStructure: 'Levantad el brazo.   —   Tocad la mano.',
    cultural: {
      heading: 'Juegos y canciones',
      fact: 'In Spain and Latin America, children learn through songs and movement — just like you!',
      detail: 'Action songs help build vocabulary fast — the brain connects the word with the action.',
    },
    activities: [
      {
        title: 'Cabeza, Hombros, Rodillas, Pies',
        icon: '🎵',
        instruction: 'Sing Heads, Shoulders, Knees and Toes — in Spanish! Follow the actions as fast as you can.',
        examples: ['Cabeza, hombros, rodillas, pies', 'Ojos, orejas, boca y nariz'],
        tip: null,
      },
      {
        title: 'Simón dice — Nivel 2',
        icon: '🎮',
        instruction: 'Now with arms and hands too! Remember: only move if you hear Simón dice.',
        examples: ['Simón dice: levantad el brazo!', 'Simón dice: tocad el hombro!'],
        tip: 'Izquierdo = left  ·  Derecho = right',
      },
      {
        title: 'Dibujad y etiquetad',
        icon: '✏️',
        instruction: 'Draw a simple outline of an arm and hand. Label as many parts as you can in Spanish.',
        examples: null,
        tip: 'Aim for 4+ labels — including ones from last lesson!',
      },
    ],
    roundOff: 'Thumb challenge: arm? Hand? Fingers? Shoulder? Neck? Tell your partner all five.',
    imgFile: null,
  },
  {
    num: 3,
    fileOut: 'Y5_Sp_T1_L03_PiernasYPies.pptx',
    titleSp: 'Las piernas y los pies',
    titleEng: 'Legs, feet and the full body',
    lo: 'Puedo decir las partes del cuerpo de la cabeza a los pies.',
    loEng: 'I can say body parts from head to toe.',
    phonicsLetter: 'LL',
    phonicsSound: 'Sounds like Y in "yes"',
    phonicsFact: 'In Spanish, LL makes a Y sound — so "cuello" sounds like KWEH-yoh, not KWEH-loh.',
    phonicsExamples: [
      { word: 'cuello', pron: 'KWEH-yoh', eng: 'neck' },
      { word: 'ella', pron: 'EH-yah', eng: 'she' },
      { word: 'Me llamo', pron: 'meh YAH-moh', eng: 'my name is' },
    ],
    counting: {
      label: '1 al 20',
      nums: [
        {n:'1',sp:'uno'},{n:'2',sp:'dos'},{n:'3',sp:'tres'},
        {n:'4',sp:'cuatro'},{n:'5',sp:'cinco'},
        {n:'6',sp:'seis'},{n:'7',sp:'siete'},{n:'8',sp:'ocho'},
        {n:'9',sp:'nueve'},{n:'10',sp:'diez'},
        {n:'11',sp:'once'},{n:'12',sp:'doce'},{n:'13',sp:'trece'},
        {n:'14',sp:'catorce'},{n:'15',sp:'quince'},
        {n:'16',sp:'dieciséis'},{n:'17',sp:'diecisiete'},{n:'18',sp:'dieciocho'},
        {n:'19',sp:'diecinueve'},{n:'20',sp:'veinte'},
      ]
    },
    warmUp: {
      title: '¡La canción!',
      instruction: 'Sing Cabeza, Hombros, Rodillas, Pies — as fast as you can! Start slow, then speed up.',
      sentence1: 'Cabeza, hombros, rodillas, pies — rodillas, pies!',
      response: 'Ojos, orejas, boca y nariz.',
    },
    vocab: [
      { sp: 'la pierna', pron: 'lah PYEHR-nah', eng: 'leg' },
      { sp: 'el pie', pron: 'el PYEH', eng: 'foot' },
      { sp: 'los pies', pron: 'loss PYEHSS', eng: 'feet' },
      { sp: 'el estómago', pron: 'el ess-TOH-mah-goh', eng: 'stomach' },
      { sp: 'el pelo', pron: 'el PEH-loh', eng: 'hair' },
    ],
    keyStructure: 'Señalad la pierna.   —   Tocad el pie.',
    cultural: {
      heading: 'El deporte en España',
      fact: 'Spain is famous for football — el fútbol. Players train their whole bodies!',
      detail: 'Real Madrid and FC Barcelona are two of the most famous clubs in the world.',
    },
    activities: [
      {
        title: 'El cuerpo completo',
        icon: '🧍',
        instruction: 'Can you say 10 body parts in order, head to toe? Point to each one as you say it.',
        examples: ['La cabeza → los hombros → los brazos → ...'],
        tip: 'Challenge: can you do it without stopping?',
      },
      {
        title: 'Encadenados',
        icon: '🔗',
        instruction: 'Body part chain! Each person adds one more word to the list.',
        examples: ['La cabeza', 'La cabeza y los ojos', 'La cabeza, los ojos y la boca...'],
        tip: 'How long can your chain get?',
      },
      {
        title: 'Dibujad y etiquetad',
        icon: '✏️',
        instruction: 'Draw a body outline and label as many parts as you can. Aim for 8 or more!',
        examples: null,
        tip: 'Use all the vocab from lessons 1, 2 and 3.',
      },
    ],
    roundOff: 'Exit ticket: write three body parts in Spanish on your whiteboard. Show your teacher.',
    imgFile: null,
  },
  {
    num: 4,
    fileOut: 'Y5_Sp_T1_L04_MeDuele.pptx',
    titleSp: '¡Me duele!',
    titleEng: 'Something hurts!',
    lo: 'Puedo decir qué me duele usando "me duele".',
    loEng: 'I can say what hurts using "me duele".',
    phonicsLetter: 'D',
    phonicsSound: 'Softer than English D',
    phonicsFact: 'Spanish D is gentler than English. Between vowels it softens to almost a "th" sound.',
    phonicsExamples: [
      { word: 'duele', pron: 'DWEH-leh', eng: 'it hurts' },
      { word: 'dedo', pron: 'DEH-doh', eng: 'finger' },
      { word: 'dos', pron: 'doss', eng: 'two' },
    ],
    counting: {
      label: '1 al 20',
      nums: [
        {n:'1',sp:'uno'},{n:'2',sp:'dos'},{n:'3',sp:'tres'},
        {n:'4',sp:'cuatro'},{n:'5',sp:'cinco'},
        {n:'6',sp:'seis'},{n:'7',sp:'siete'},{n:'8',sp:'ocho'},
        {n:'9',sp:'nueve'},{n:'10',sp:'diez'},
        {n:'11',sp:'once'},{n:'12',sp:'doce'},{n:'13',sp:'trece'},
        {n:'14',sp:'catorce'},{n:'15',sp:'quince'},
        {n:'16',sp:'dieciséis'},{n:'17',sp:'diecisiete'},{n:'18',sp:'dieciocho'},
        {n:'19',sp:'diecinueve'},{n:'20',sp:'veinte'},
      ]
    },
    warmUp: {
      title: 'Repaso veloz',
      instruction: 'Quick-fire! Teacher points to a body part — class says it in Spanish together.',
      sentence1: 'Head → la cabeza   Arm → el brazo   Leg → la pierna',
      response: 'Foot → el pie   Stomach → el estómago   Hair → el pelo',
    },
    vocab: [
      { sp: 'me duele', pron: 'meh DWEH-leh', eng: 'it hurts (me)' },
      { sp: '¿Qué te duele?', pron: 'keh teh DWEH-leh', eng: 'What hurts (you)?' },
      { sp: 'enfermo/a', pron: 'en-FEHR-moh/ah', eng: 'ill / sick' },
      { sp: 'mejor', pron: 'meh-HOR', eng: 'better' },
      { sp: 'la farmacia', pron: 'lah far-MAH-thyah', eng: 'the pharmacy' },
    ],
    keyStructure: 'Me duele la cabeza.   —   Me duele el brazo.',
    cultural: {
      heading: 'La farmacia española',
      fact: 'Spain has over 22,000 pharmacies — look for the glowing green cross sign!',
      detail: 'Pharmacists (farmacéuticos) give advice and help — and they speak Spanish, of course!',
    },
    activities: [
      {
        title: 'Al médico — modelo',
        icon: '👨‍⚕️',
        instruction: 'Listen to the doctor role play. Which body part hurts each patient?',
        examples: ['¿Qué te duele? — Me duele la cabeza.', '¿Qué te duele? — Me duele el estómago.'],
        tip: null,
      },
      {
        title: 'Escuchad y señalad',
        icon: '👂',
        instruction: 'Listen to 6 sentences. Which body part hurts? Point to it each time.',
        examples: null,
        tip: 'Listen for the word AFTER "me duele" — that is the body part!',
      },
      {
        title: 'El juego del médico',
        icon: '🎭',
        instruction: 'Role play in pairs! One is the doctor, one is the patient. Swap after 2 turns.',
        examples: ['Doctor: ¿Qué te duele?', 'Patient: Me duele... [point to a body part]'],
        tip: null,
      },
    ],
    roundOff: 'How do you say MY HEAD HURTS in Spanish? Show with an action too!',
    imgFile: null,
  },
  {
    num: 5,
    fileOut: 'Y5_Sp_T1_L05_MeDuelen.pptx',
    titleSp: '¡Me duelen!',
    titleEng: 'More than one thing hurts!',
    lo: 'Puedo distinguir entre "me duele" y "me duelen".',
    loEng: 'I can tell the difference between "me duele" and "me duelen".',
    phonicsLetter: 'Z',
    phonicsSound: 'Like TH in "think"',
    phonicsFact: 'In Spain, Z sounds like "th" in think. In Latin America it sounds like S. Both are correct!',
    phonicsExamples: [
      { word: 'nariz', pron: 'nah-REETH', eng: 'nose' },
      { word: 'cabeza', pron: 'kah-BEH-thah', eng: 'head' },
      { word: 'diez', pron: 'DYETH', eng: 'ten' },
    ],
    counting: {
      label: '1 al 20',
      nums: [
        {n:'1',sp:'uno'},{n:'2',sp:'dos'},{n:'3',sp:'tres'},
        {n:'4',sp:'cuatro'},{n:'5',sp:'cinco'},
        {n:'6',sp:'seis'},{n:'7',sp:'siete'},{n:'8',sp:'ocho'},
        {n:'9',sp:'nueve'},{n:'10',sp:'diez'},
        {n:'11',sp:'once'},{n:'12',sp:'doce'},{n:'13',sp:'trece'},
        {n:'14',sp:'catorce'},{n:'15',sp:'quince'},
        {n:'16',sp:'dieciséis'},{n:'17',sp:'diecisiete'},{n:'18',sp:'dieciocho'},
        {n:'19',sp:'diecinueve'},{n:'20',sp:'veinte'},
      ]
    },
    warmUp: {
      title: '¿Qué te duele?',
      instruction: 'Partner quiz! Partner A acts out something hurting — Partner B says the Spanish sentence.',
      sentence1: 'Me duele la cabeza  /  el brazo  /  la pierna  /  el pie',
      response: 'Can you say it and point at the same time?',
    },
    vocab: [
      { sp: 'me duelen', pron: 'meh DWEH-len', eng: 'they hurt (me) — plural' },
      { sp: 'me duele', pron: 'meh DWEH-leh', eng: 'it hurts (me) — singular' },
      { sp: 'los ojos', pron: 'loss OH-hoss', eng: 'the eyes (plural)' },
      { sp: 'las piernas', pron: 'lass PYEHR-nass', eng: 'the legs (plural)' },
      { sp: 'los brazos', pron: 'loss BRAH-thoss', eng: 'the arms (plural)' },
    ],
    keyStructure: 'Me duele la pierna.   ↔   Me duelen las piernas.',
    cultural: {
      heading: 'El español en América Latina',
      fact: 'Spanish is spoken across 19 countries in Latin America — from Mexico to Argentina!',
      detail: 'Over 400 million people in Latin America speak Spanish as their first language.',
    },
    activities: [
      {
        title: 'Singular o plural',
        icon: '⚖️',
        instruction: 'Listen to each sentence. Thumbs up for ME DUELE (one thing), thumbs down for ME DUELEN (more than one).',
        examples: ['Me duele el ojo.  👍  — one eye', 'Me duelen las manos.  👎  — both hands'],
        tip: null,
      },
      {
        title: 'La encuesta',
        icon: '📋',
        instruction: 'Class survey! Ask 4 friends: ¿Qué te duele hoy? Write their answers down.',
        examples: ['¿Qué te duele?   →   Me duele... / Me duelen...'],
        tip: null,
      },
      {
        title: 'Escribid seis frases',
        icon: '✏️',
        instruction: 'Write 3 sentences using ME DUELE and 3 using ME DUELEN. Use different body parts each time.',
        examples: null,
        tip: 'Singular: el ojo, la mano, el pie  ·  Plural: los ojos, las manos, los pies',
      },
    ],
    roundOff: 'Key question: when do you use ME DUELE and when ME DUELEN? Explain the rule to your partner.',
    imgFile: null,
  },
  {
    num: 6,
    fileOut: 'Y5_Sp_T1_L06_Repaso.pptx',
    titleSp: '¡Repaso!',
    titleEng: 'Review — Putting it all together',
    lo: 'Puedo usar el vocabulario del cuerpo y "me duele/me duelen" en conversación.',
    loEng: 'I can use body vocabulary and "me duele/me duelen" in a conversation.',
    phonicsLetter: 'RR',
    phonicsSound: 'A rolled or trilled R',
    phonicsFact: 'RR is a rolled R — made by flapping your tongue quickly against the roof of your mouth.',
    phonicsExamples: [
      { word: 'perro', pron: 'PEHR-roh', eng: 'dog' },
      { word: 'arriba', pron: 'ah-REE-bah', eng: 'above / up' },
      { word: 'tierra', pron: 'TYEHR-rah', eng: 'earth / land' },
    ],
    counting: {
      label: '1 al 20',
      nums: [
        {n:'1',sp:'uno'},{n:'2',sp:'dos'},{n:'3',sp:'tres'},
        {n:'4',sp:'cuatro'},{n:'5',sp:'cinco'},
        {n:'6',sp:'seis'},{n:'7',sp:'siete'},{n:'8',sp:'ocho'},
        {n:'9',sp:'nueve'},{n:'10',sp:'diez'},
        {n:'11',sp:'once'},{n:'12',sp:'doce'},{n:'13',sp:'trece'},
        {n:'14',sp:'catorce'},{n:'15',sp:'quince'},
        {n:'16',sp:'dieciséis'},{n:'17',sp:'diecisiete'},{n:'18',sp:'dieciocho'},
        {n:'19',sp:'diecinueve'},{n:'20',sp:'veinte'},
      ]
    },
    warmUp: {
      title: 'Vocabulario veloz',
      instruction: 'Speed round! Teacher calls English — class says Spanish. Then swap roles.',
      sentence1: 'Head · Eyes · Nose · Mouth · Ears · Arm · Hand · Leg · Foot · Stomach',
      response: '¡Rápido, rápido!',
    },
    vocab: [
      { sp: 'la cabeza, los ojos', pron: 'head, eyes', eng: 'Review: face' },
      { sp: 'el brazo, la mano', pron: 'arm, hand', eng: 'Review: upper body' },
      { sp: 'la pierna, el pie', pron: 'leg, foot', eng: 'Review: lower body' },
      { sp: 'me duele + singular', pron: 'meh DWEH-leh', eng: 'one body part hurts' },
      { sp: 'me duelen + plural', pron: 'meh DWEH-len', eng: 'more than one hurts' },
    ],
    keyStructure: '¿Qué te duele?   —   Me duele/n...',
    cultural: null, // card fallback — vocab review layout
    activities: [
      {
        title: 'Simón dice — Gran repaso',
        icon: '🎮',
        instruction: 'Full body Simón dice using everything from this term. Speed it up! Whoever makes a mistake is out.',
        examples: null,
        tip: 'Use all the body parts you know — head, face, arms, legs and more!',
      },
      {
        title: 'El médico — juego extendido',
        icon: '👨‍⚕️',
        instruction: 'Extended role play: patient, doctor, and a waiting room. Use all your vocabulary.',
        examples: ['¿Qué te duele?', 'Me duelen los ojos y me duele la cabeza.', '¡Ay, pobre! Estás enfermo/a.'],
        tip: null,
      },
      {
        title: 'Evaluación hablada',
        icon: '⭐',
        instruction: 'Speaking check! Tell your teacher: 5 body parts, one me duele sentence, one me duelen sentence.',
        examples: null,
        tip: 'Aim for: 8+ body parts and correct use of me duele / me duelen.',
      },
    ],
    roundOff: '¡Hasta luego! What is your favourite Spanish word from this term? Tell your partner.',
    imgFile: null,
  },
];
