"""
generate_mtp.py

Validates and saves a Medium Term Plan JSON for an enquiry unit.
The MTP is generated by Claude in chat, then passed to this script to validate
and save before building begins.

Usage:
    python3 generate_mtp.py mtp.json      # validate only
    python3 generate_mtp.py mtp.json --check-images   # also report missing image paths
"""

import sys, json, os
from pathlib import Path

VALID_SLIDE_TYPES = {
    'cover', 'lo', 'recall', 'teaching', 'discussion', 'activity',
    'misconception', 'fed_in_facts', 'quiz', 'quiz_answers', 'learning_review'
}
VALID_LAYOUTS = {
    'text_only', 'image_grid', 'provocation', 'comparison',
    'image_right', 'image_left', 'diagram_annotated'
}
VALID_MODES = {'ido', 'wedo', 'youdo', 'youdo_trio'}

REQUIRED_ENQUIRY = {'subject', 'key_question', 'challenge', 'num_lessons'}
REQUIRED_LESSON  = {'number', 'day', 'lo', 'tib', 'isb', 'slides'}

def error(msg): print(f"  ERROR: {msg}")
def warn(msg):  print(f"  WARN:  {msg}")
def ok(msg):    print(f"  OK:    {msg}")

def validate(mtp, check_images=False):
    errors = 0

    # Enquiry level
    enq = mtp.get('enquiry', {})
    for k in REQUIRED_ENQUIRY:
        if k not in enq:
            error(f"enquiry.{k} missing")
            errors += 1

    lessons = mtp.get('lessons', [])
    if not lessons:
        error("No lessons defined")
        errors += 1

    for lesson in lessons:
        n = lesson.get('number', '?')
        for k in REQUIRED_LESSON:
            if k not in lesson:
                error(f"Lesson {n}: {k} missing")
                errors += 1

        slides = lesson.get('slides', [])
        has_cover = any(s.get('type') == 'cover' for s in slides)
        has_lo    = any(s.get('type') == 'lo' for s in slides)
        has_lr    = any(s.get('type') == 'learning_review' for s in slides)

        if not has_cover: warn(f"Lesson {n}: no cover slide")
        if not has_lo:    warn(f"Lesson {n}: no lo slide")
        if not has_lr:    warn(f"Lesson {n}: no learning_review slide")

        for i, slide in enumerate(slides):
            stype  = slide.get('type', '')
            layout = slide.get('layout', 'text_only')
            mode   = slide.get('mode', '')

            if stype not in VALID_SLIDE_TYPES:
                error(f"Lesson {n} slide {i}: unknown type '{stype}'")
                errors += 1

            if layout not in VALID_LAYOUTS:
                error(f"Lesson {n} slide {i}: unknown layout '{layout}'")
                errors += 1

            if mode and mode not in VALID_MODES:
                warn(f"Lesson {n} slide {i}: unknown mode '{mode}'")

            # Check images have paths if check_images
            if check_images and layout != 'text_only':
                images = slide.get('images', [])
                grid_items = slide.get('grid', {}).get('items', [])
                all_items = images + grid_items
                for j, item in enumerate(all_items):
                    path = item.get('path', '')
                    if not path:
                        warn(f"Lesson {n} slide {i} image {j}: no path set (not yet generated)")
                    elif not os.path.exists(path):
                        error(f"Lesson {n} slide {i} image {j}: path not found: {path}")
                        errors += 1

    if errors == 0:
        print(f"✓ MTP valid — {len(lessons)} lessons, ready to build")
    else:
        print(f"✗ {errors} error(s) found — fix before building")
    return errors == 0

def save(mtp, path):
    with open(path, 'w') as f:
        json.dump(mtp, f, indent=2, ensure_ascii=False)
    print(f"Saved: {path}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python3 generate_mtp.py mtp.json [--check-images]")
        sys.exit(1)
    path = sys.argv[1]
    check_images = '--check-images' in sys.argv
    with open(path) as f:
        mtp = json.load(f)
    ok_flag = validate(mtp, check_images)
    sys.exit(0 if ok_flag else 1)
